// Generated by CoffeeScript 1.10.0
(function() {
  var App;

  App = (typeof exports !== "undefined" && exports !== null) && exports || (this.App = {});

  App.octo = new Octokat();

  App.Github = (function() {
    function Github() {}

    Github.rateLimit = function(callback) {
      return App.octo.rateLimit.fetch(function(err, data) {
        return callback({
          limit: data.rate.limit,
          remaining: data.rate.remaining,
          hasRemaining: function() {
            return data.rate.remaining > 0;
          }
        });
      });
    };

    return Github;

  })();

}).call(this);
