// Generated by CoffeeScript 1.10.0
(function() {
  var App;

  App = (typeof exports !== "undefined" && exports !== null) && exports || (this.App = {});

  App.octo = new Octokat();

  App.Github = (function() {
    function Github() {}

    Github.rateLimit = function(callback) {
      return App.octo.rateLimit.fetch(function(err, data) {
        if (err) {
          return console.log(err);
        } else {
          return callback({
            limit: data.rate.limit,
            remaining: data.rate.remaining,
            hasRemaining: function() {
              return data.rate.remaining > 0;
            }
          });
        }
      });
    };

    Github.oneMonthAgo = function() {
      var result;
      result = new Date;
      result.setMonth(result.getMonth() - 1);
      return this.dateFormat(result);
    };

    Github.dateFormat = function(d) {
      return d.getFullYear() + '-' + (d.getMonth() + 1) + '-' + d.getDate();
    };

    return Github;

  })();

}).call(this);
