// Generated by CoffeeScript 1.10.0
(function() {
  var App;

  App = (typeof exports !== "undefined" && exports !== null) && exports || (this.App = {});

  App.Repo = (function() {
    function Repo(repo_spec) {
      var parts;
      parts = repo_spec.split('/');
      this.acct = parts[0];
      this.name = parts[1];
      this.rawdata = {};
      this.octo = new Octokat;
      this.fetchData();
    }

    Repo.prototype.fetchData = function() {
      return this.octo.repos(this.acct, this.name).fetch(function(err, repodata) {
        if (err) {
          return alert(err);
        } else {
          this.rawdata.repo = repodata;
          return fetchAll(this.octo.repos(this.acct, this.name).issues.fetch).then(function(allIssues) {
            this.rawdata.open_issues = allIssues;
            return console.log(repo);
          });
        }
      });
    };

    return Repo;

  })();

}).call(this);
