// Generated by CoffeeScript 1.10.0
(function() {
  var App,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  App = (typeof exports !== "undefined" && exports !== null) && exports || (this.App = {});

  App.Repo = (function() {
    function Repo(repo_spec) {
      this.fetchIssues = bind(this.fetchIssues, this);
      this.fetchData = bind(this.fetchData, this);
      var ref;
      ref = repo_spec.split('/'), this.acct = ref[0], this.name = ref[1];
      this.rawdata = {};
      this.octo = new Octokat();
      this.fetchData();
    }

    Repo.prototype.fetchData = function() {
      return this.octo.repos(this.acct, this.name).fetch((function(_this) {
        return function(err, repodata) {
          if (err) {
            return alert(err);
          } else {
            _this.rawdata.repo = repodata;
            return _this.fetchIssues();
          }
        };
      })(this));
    };

    Repo.prototype.fetchIssues = function() {
      fetchAll(this.octo.repos(this.acct, this.name).issues.fetch, {
        state: 'open'
      }).then((function(_this) {
        return function(openIssues) {
          return _this.rawdata.openIssues = openIssues;
        };
      })(this));
      return fetchAll(this.octo.repos(this.acct, this.name).issues.fetch, {
        state: 'closed'
      }).then((function(_this) {
        return function(closedIssues) {
          return _this.rawdata.closedIssues = closedIssues;
        };
      })(this));
    };

    return Repo;

  })();

}).call(this);
