// Generated by CoffeeScript 1.10.0
(function() {
  App.UI = (function() {
    function UI() {}

    UI.hideProgressBar = function() {
      return $('div.progress').hide('fast');
    };

    UI.showProgressBar = function() {
      return $('div.progress').show('fast');
    };

    UI.setProgress = function(percent) {
      return $('.progress-bar').attr('style', 'width: ' + percent + '%');
    };

    return UI;

  })();

}).call(this);
