// Generated by CoffeeScript 1.10.0
(function() {
  App.UI = (function() {
    function UI() {}

    UI.anonymousMode = function() {};

    UI.signedInMode = function(username) {};

    UI.progress = function(percent) {
      if (percent > 0) {
        this._changeProgress();
        return this.showProgressBar();
      } else {
        this.hideProgressBar();
        return this._changeProgress();
      }
    };

    UI.hideProgressBar = function() {
      return $('div.progress').hide('fast');
    };

    UI.showProgressBar = function() {
      return $('div.progress').show('fast');
    };

    UI._changeProgress = function(percent) {
      return $('.progress-bar').attr('style', 'width: ' + percent + '%');
    };

    return UI;

  })();

}).call(this);
